# Generated by Django 2.2.4 on 2019-08-13 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0002_article_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='created_by',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING,
                                    related_name='articles', to=settings.AUTH_USER_MODEL),
        ),
    ]
